# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26850129ed6fff2283b366876992dc40696fdc349273006eb56276351b2d0c7d4f7cb430c9441c0840db7412532a81daf6eb90a7c24144d123546e7e7c46a40

test:
  secret_key_base: afa9b1292cdd800a1f9c664ef6ca831a64cdaf58e75a89c2c33ca04ca69cd708792d7e9190e10a08034a92108f06cd2a00877d5c0f9c06c870dcfdf545a4d43c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
